<?php

namespace Acme\StoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProductController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\StoreBundle\Controller\ProductController();
        return $instance;
    }
}
