<?php

namespace Admingenerator\GeneratorBundle\Controller\DoctrineODM;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BaseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Admingenerator\GeneratorBundle\Controller\DoctrineODM\BaseController();
        return $instance;
    }
}
