<?php

namespace Admingenerator\GeneratorBundle\Controller\Doctrine;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BaseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Admingenerator\GeneratorBundle\Controller\Doctrine\BaseController();
        return $instance;
    }
}
