<?php

namespace Kingston\HyperxBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ReviewController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Kingston\HyperxBundle\Controller\ReviewController();
        return $instance;
    }
}
